/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STDTYPES.h"
#include "BIT_MATH.h"
#include "errorstate.h"
#include "stm32f103xx.h"
#include "RCC_Interface.h"
#include "GPIO_Priv.h"
#include "SYSTICK_Priv.h"
#include "GPIO_Interface.h"
#include "SYSTICK_Interface.h"
#include "UART_Interface.h"
#include "PH_Interface.h"
#include "DS18B20.h"
f32 App_ph_f32Value;
f32 App_TempuratureVal;
u16_t App_phBuff[10];
u8_t App_ph_str[7];
u8_t App_indexoF_Ph_str;

u8_t App_Temp_str[7];
u8_t App_indexoF_Temp_str;

int main(void)
{
	RCC_voidSelectClock(HSI);
	SYSTICK_enuInit(PRESSCALER_8);
	UART_vInit(Baudrate_115200,DISABLE_INTERRUPTS);
	pH_enuInit(ADC5);

    while(1)
    {

      pH_enuReadValue(App_phBuff, &App_ph_f32Value);
      ConvertFloatToString(App_ph_f32Value,&App_ph_str);
      ConverFracToString(App_ph_f32Value,&App_ph_str,&App_indexoF_Ph_str);
      UART_vSendStream(&App_ph_str,App_indexoF_Ph_str);
      SYSTICK_enuDelay_us(1000000);
      App_TempuratureVal = DS18B20_read_temp_celsius();
      ConvertFloatToString(App_TempuratureVal, &App_Temp_str);
      ConverFracToString(App_TempuratureVal, &App_Temp_str,&App_indexoF_Temp_str);
      SYSTICK_enuDelay_us(7000000);

    }

}
